title: <p align="center"> Parthasarathy Seshadri </p>
logo: /images/mypicture.png

description:
  <p align="center">
   <a href="https://www.linkedin.com/in/parthasarathy-seshadri-7340a461/">LinkedIn</a> |
  <a href="https://github.com/parthakrs">GitHub</a>  
  <br>   
  I'm working on  Software Architect on OIL and Gas Domain.
  Currenly learning Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>
theme: jekyll-theme-minimal
